### ISSUE TITLE
[Tracking] Add CI tests

### ISSUE THREAD

**Issue by ktbarrett** [ktbarrett/find_libpython#4]
Add tests for all supported environments to CI and list known working environment. Also should be collecting coverage.

- [x] Formatting - Black (#8)
- [x] Debian/Ubuntu - System (#10)
- [x] Arch - System (#21)
- [x] Alpine - System (#22)
- [x] RHEL 7 - System (#14 and #36)
- [x] RHEL 7 - Appstream (#36 and #38)
- [x] RHEL 8 - System (#36)
- [x] RHEL 8 - Appstream (#36)
- [x] RHEL 9 - System (#40)
- [x] Linux - python.org (#28)
- [x] Linux - Conda (#11)
- [ ] Linux - Conda 32 bit (#13)
- [ ] Windows - Chocolately
- [x] Windows/msys2 - System (#16)
- [x] Windows/mingw-w32/64 - System (#16)
- [x] Windows - python.org Installer (#28)
- [x] Windows - Conda (#12)
- [ ] Windows - Conda 32 bit (#13)
- [x] Mac OS - Homebrew (#19)
- [x] Mac OS - python.org Installer (#28)
- [x] Mac OS - Conda (#12)

**Comment by ktbarrett** [comment]
The Python installation for Chocolately is just the python.org installer. And we can't really test the 32-bit miniconda environment anymore, so I'm fine with dropping support. I'm calling this done for now.
